version: '3.7'

services:
  php-fpm:
    container_name: cigniter4-php-fpm
    build: .
    volumes:
      - ./cigniter-app:/var/www/html
    networks:
      - cigniter-network

  nginx:
    image: nginx:latest
    container_name: cigniter4-nginx
    volumes:
      - ./cigniter-app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - cigniter-network

  mysql_db:
    image: mysql:latest
    container_name: cigniter4-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion-projet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - cigniter-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cigniter4-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    networks:
      - cigniter-network

volumes:
  mysql_data:

networks:
  cigniter-network:
    driver: bridge
